remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

sass:
  style: compressed

include:
  - assets/css/custom.css

defaults:
  - scope:
      path: ""
    values:
      layout: default
